climate:
  - platform: haier
    id: ${device_id}
    protocol: hOn
    name: ${device_name}
    uart_id: ${uart_id}
    wifi_signal: ${send_wifi}   # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    outdoor_temperature:        # Optional, outdoor temperature sensor
      name: ${device_name} outdoor temperature
    indoor_coil_temperature:
      name: ${device_name} Indoor Coil Temperature
    outdoor_coil_temperature:
      name: ${device_name} Outdoor Coil Temperature
    outdoor_defrost_temperature:
      name: ${device_name} Outdoor Defrost Temperature
    outdoor_in_air_temperature:
      name: ${device_name} Outdoor In Air Temperature
    outdoor_out_air_temperature:
      name: ${device_name} Outdoor Out Air Temperature
    power:
      name: ${device_name} Power
    compressor_frequency:
      name: ${device_name} Compressor Frequency
    compressor_current:
      name: ${device_name} Compressor Current
    expansion_valve_open_degree:
      name: ${device_name} Expansion Valve Open Degree
    outdoor_fan_status:
      name: ${device_name} Outdoor Fan Status
    defrost_status:
      name: ${device_name} Defrost Status
    compressor_status:
      name: ${device_name} Compressor Status
    indoor_fan_status:
      name: ${device_name} Indoor Fan Status
    four_way_valve_status:
      name: ${device_name} Four-way Valve Status
    indoor_electric_heating_status:
      name: ${device_name} Indoor Electric Heating Status
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 
        target_temperature: 1
        current_temperature: 0.5
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
      - 'OFF'                     # always available
      - HEAT_COOL                 # always available
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
      - 'OFF'
      - VERTICAL
      - HORIZONTAL
      - BOTH
    supported_presets:          # Optional, can be used to disable some presets if your AC does not support it
      - ECO
      - BOOST
      - SLEEP
    # Next two triggers calling Home Assistant services to notify user about alarms triggered by AC
    # this functionality is disabled by default. To enable it check "Allow the device to make Home Assistant service calls"
    # checkbox in Home Assistant's device settings
    on_alarm_start:
      then:
        - homeassistant.service:
            service: logbook.log
            data:
              domain: climate
              name: ${device_name}
            data_template:
              message: "Alarm activated ({{ alarm_code }}): {{alarm_message}}" 
            variables:
              alarm_message: !lambda "return message;"
              alarm_code: !lambda "return code;"
        - homeassistant.service:
            service: notify.persistent_notification
            data:
              title: "${device_name}: alarm activated"
            data_template:
              message: "Code: {{ alarm_code }}, message: \"{{ alarm_message }}\""
            variables:
              alarm_message: !lambda "return message;"
              alarm_code: !lambda "return code;"
    on_alarm_end:
      then:
        - homeassistant.service:
            service: logbook.log
            data:
              domain: climate
              name: ${device_name}
            data_template:
              message: "Alarm deactivated ({{ alarm_code }}): {{alarm_message}}" 
            variables:
              alarm_message: !lambda "return message;"
              alarm_code: !lambda "return code;"
